image: test:10
image_repo: test
container: tester # or dirname
network: test
ports:
  1000: 2000
volumes:
  /data: /tmp
env:
  A: 1
env_file: test.env
modes:
  - name: dev
    container: tester-x
    port_offset: 1
    ports:
      1010: 2010
    volumes:
      /data: /tmp-dev
    env:
      A: 2
      B: '3'
    env_file: test-dev.env
